name: CI - Build and deploy (release to nuget)

on: 
  push:
    branches:
    - release

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '2.2.x'

    - if: github.ref == 'refs/heads/release' 
      name: Run the build and deploy script
      run: ./build/build.sh deploy
      env:
        NUGET_AUTH_TOKEN: ${{secrets.NUGET_AUTH_TOKEN}}
